---
- name: Add PHP 7.3 to source list
  apt_repository: repo="ppa:ondrej/php" state=present

- name: Install PHP 7.3
  apt: name={{item}} state=latest
  with_items:
    - php7.3
    - php7.3-cli
    - php7.3-common
    - php7.3-curl
    - php7.3-dev
    - php7.3-gd
    - php7.3-mbstring
    - php7.3-zip
    - php7.3-mysql
    - php7.3-xml
    - php7.3-fpm
    - php7.3-imagick
    - php7.3-recode
    - php7.3-tidy
    - php7.3-xmlrpc
    - php7.3-intl

- name: Configure PHP 7.3 settings
  lineinfile: dest=/etc/php/7.3/cli/php.ini regexp="^{{ item.param }} =" line="{{ item.param }} = {{ item.value }}"
  with_items :
    - { param: error_reporting, value: "E_ALL" }
    - { param: display_errors, value: "On" }
    - { param: post_max_size, value: "128M" }
    - { param: upload_max_filesize, value: "128M" }
    - { param: memory_limit, value: "512M" }
    - { param: max_input_time, value: "30" }
    - { param: max_execution_time, value: "30" }
    - { param: short_open_tag, value: "Off" }
    - { param: date.timezone , value: "Europe/Paris" }
    - { param: cgi.fix_pathinfo , value: "0" }
    - { param: phar.readonly , value: "Off" }
    - { param: expose_php , value: "Off" }

- name: Configure PHP 7.3 FPM settings
  lineinfile: dest=/etc/php/7.3/fpm/pool.d/www.conf regexp="^{{ item.param }} =" line="{{ item.param }} = {{ item.value }}"
  with_items :
    - { param: user, value: "{{ php73.run_as }}" }
    - { param: group, value: "{{ php73.run_as }}" }
    - { param: listen.owner, value: "{{ php73.run_as }}" }
    - { param: listen.group, value: "{{ php73.run_as }}" }
    - { param: listen.mode, value: "0666" }

- name: "Ensure PHP 7.3 FPM is {{ php73.start | ternary('started','stopped') }}"
  service: name="php7.3-fpm" state={{ php73.start | ternary('restarted','stopped') }} enabled={{ php73.service_enabled }}
