---
- name: Add PHP 7.2 to source list
  apt_repository: repo="ppa:ondrej/php" state=present

- name: Install PHP 7.2
  apt: name={{item}} state=latest
  with_items:
    - php7.2
    - php7.2-cli
    - php7.2-common
    - php7.2-bcmath
    - php7.2-ctype
    - php7.2-curl
    - php7.2-dom
    - php7.2-fpm
    - php7.2-gd
    - php7.2-iconv
    - php7.2-intl
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-simplexml
    - php7.2-soap
    - php7.2-xsl
    - php7.2-zip

- name: Configure PHP 7.2 settings
  lineinfile: dest=/etc/php/7.2/cli/php.ini regexp="^{{ item.param }} =" line="{{ item.param }} = {{ item.value }}"
  with_items :
    - { param: error_reporting, value: "E_ALL" }
    - { param: display_errors, value: "On" }
    - { param: post_max_size, value: "256M" }
    - { param: upload_max_filesize, value: "256M" }
    - { param: memory_limit, value: "768M" }
    - { param: max_input_time, value: "30" }
    - { param: max_execution_time, value: "30" }
    - { param: short_open_tag, value: "Off" }
    - { param: date.timezone , value: "Europe/Paris" }
    - { param: cgi.fix_pathinfo , value: "0" }
    - { param: phar.readonly , value: "Off" }
    - { param: expose_php , value: "Off" }

- name: Configure PHP 7.2 FPM settings
  lineinfile: dest=/etc/php/7.2/fpm/pool.d/www.conf regexp="^{{ item.param }} =" line="{{ item.param }} = {{ item.value }}"
  with_items :
    - { param: user, value: "{{ php73.run_as }}" }
    - { param: group, value: "{{ php73.run_as }}" }
    - { param: listen.owner, value: "{{ php73.run_as }}" }
    - { param: listen.group, value: "{{ php73.run_as }}" }
    - { param: listen.mode, value: "0666" }

- name: "Ensure PHP 7.2 FPM is {{ php73.start | ternary('started','stopped') }}"
  service: name="php7.2-fpm" state={{ php73.start | ternary('restarted','stopped') }} enabled={{ php73.service_enabled }}
